
# Font stuff
font_family      family="Berkeley Mono Regular"
italic_font      auto
bold_font        auto
bold_italic_font auto

font_size        11.0

# Nerd Fonts v3.2.0
symbol_map U+e000-U+e00a,U+ea60-U+ebeb,U+e0a0-U+e0c8,U+e0ca,U+e0cc-U+e0d7,U+e200-U+e2a9,U+e300-U+e3e3,U+e5fa-U+e6b1,U+e700-U+e7c5,U+ed00-U+efc1,U+f000-U+f2ff,U+f000-U+f2e0,U+f300-U+f372,U+f400-U+f533,U+f0001-U+f1af0 Symbols Nerd Font Mono

# Transparency
background_opacity  0.85

foreground                      #cccccc
background                      #181818
selection_foreground            none
selection_background            #264f78

cursor                          #aeafad
cursor_text_color               #181818

url_color                       #3b8eea

active_border_color             #2472c8
inactive_border_color           #2b2b2b
bell_border_color               #e5e510
visual_bell_color               none

wayland_titlebar_color          system
macos_titlebar_color            system

active_tab_background           #1f1f1f
active_tab_foreground           #ffffff
inactive_tab_background         #181818
inactive_tab_foreground         #9d9d9d
tab_bar_background              #181818
tab_bar_margin_color            none

# Set up term-colors (Cursor Dark)

#: black
color0                          #000000
color8                          #666666

#: red
color1                          #cd3131
color9                          #f14c4c

#: green
color2                          #0dbc79
color10                         #23d18b

#: yellow
color3                          #e5e510
color11                         #f5f543

#: blue
color4                          #2472c8
color12                         #3b8eea

#: magenta
color5                          #bc3fbc
color13                         #d670d6

#: cyan
color6                          #11a8cd
color14                         #29b8db

#: white
color7                          #e5e5e5
color15                         #e5e5e5


# The cursor shape can be one of (block, beam, underline)
shell_integration           no-cursor
cursor_shape                block
cursor_blink_interval       0.5
cursor_stop_blinking_after  15.0

# Number of lines of history to keep in memory for scrolling back
scrollback_lines        2000
scrollback_pager        less +G -R
wheel_scroll_multiplier 5.0

# The width (in pts) of window borders. Will be rounded to the nearest number of pixels based on screen resolution.
window_border_width 0
window_margin_width 20


# Manage font size
map ctrl+shift+up           increase_font_size
map ctrl+shift+down         decrease_font_size
map ctrl+shift+backspace    restore_font_size


# Misc stuff 
enable_audio_bell       yes
#open_url_modifiers      ctrl+shift
term                    xterm-kitty
open_url_with           default
allow_remote_control    yes
confirm_os_window_close 0
